#!/usr/bin/expect
set timeout 10
set CMDLINE [lindex $argv 0]
log_user 1
spawn elvish
send "echo EXPECT_START; \$edit:completion:arg-completer\[(echo $CMDLINE | awk '{print \$1}')\] $CMDLINE'' | to-json | each \[c\]{ echo \$c }; echo EXPECT_END"
send "\r"
expect -re "EXPECT_START\r\n(.*?)EXPECT_END"
puts "$expect_out(1,string)"
send "exit\r"
expect eof
